apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\0_COMMON\kompose\kompose-windows-amd64.exe --file .\docker-compose.yml convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: D:\0_COMMON\kompose\kompose-windows-amd64.exe --file .\docker-compose.yml convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:4005/validate
            - name: BILLING_SERVICE_URL
              value: http://billing-service:4001
            - name: PATIENT_SERVICE_URL
              value: http://patient-service:4000
            - name: SERVER_PORT
              value: "4004"
            - name: SPRING_PROFILE
              value: development
          image: api-gateway
          name: api-gateway
          ports:
            - containerPort: 4004
              protocol: TCP
      restartPolicy: Always
