apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\0_COMMON\kompose\kompose-windows-amd64.exe --file .\docker-compose.yml convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "4004"
      port: 4004
      targetPort: 4004
  selector:
    io.kompose.service: api-gateway
