apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\0_COMMON\kompose\kompose-windows-amd64.exe --file .\docker-compose.yml convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: billing-service
  name: billing-service
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    io.kompose.service: billing-service
