apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\0_COMMON\kompose\kompose-windows-amd64.exe --file .\docker-compose.yml convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: patient-service
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: patient-service
  template:
    metadata:
      annotations:
        kompose.cmd: D:\0_COMMON\kompose\kompose-windows-amd64.exe --file .\docker-compose.yml convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: patient-service
    spec:
      containers:
        - env:
            - name: BILLING_SERVICE_ADDRESS
              value: billing-service
            - name: BILLING_SERVICE_GRPC_PORT
              value: "9001"
            - name: KAFKA_CONSUMER_GROUP
              value: patient-service-group
            - name: KAFKA_TOPIC
              value: patient-events
            - name: SERVER_PORT
              value: "4000"
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://patient-service-db:5432/db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin_user
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_PROFILE
              value: development
          image: patient-service
          name: patient-service
          ports:
            - containerPort: 4000
              protocol: TCP
      restartPolicy: Always
